package handler

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/Mininglamp-OSS/octo-smart-summary/internal/model"
	"gorm.io/gorm"
)

// buildReferencedSummariesContext fetches the referenced summary tasks and
// their latest agent-generated PersonalResult snapshots, then formats them
// into a single string block that can be appended to the agent's system
// prompt. Used when the user starts a new chat session while referencing
// one or more existing summaries (see CHAT-REFERENCE-BASED-DESIGN-v1).
//
// Design notes:
//   - Only invoked on the FIRST turn of a session (when LoadHistory returns
//     empty). Later turns rely on the injected system message being cached
//     in the LLM context.
//   - Space boundary enforced: tasks not belonging to the caller's space
//     are silently dropped (not an error — logged so the caller can decide
//     whether to surface an "some references unavailable" hint).
//   - Reference material is APPENDED to the profile's system prompt (not
//     prepended), so agent's baseline behavior (from profile.md) still
//     takes precedence.
//   - If none of the requested task IDs are accessible, returns "" (caller
//     should treat as "no reference material" and proceed with normal chat).
//
// Returns:
//   - context string (empty if no valid references)
//   - list of successfully-loaded task IDs (for logging / persistence)
func buildReferencedSummariesContext(
	ctx context.Context,
	db *gorm.DB,
	spaceID string,
	userID string,
	taskIDs []int64,
) (string, []int64, error) {
	if len(taskIDs) == 0 {
		return "", nil, nil
	}

	// Fetch tasks in one query, then filter to caller's space
	var tasks []model.SummaryTask
	if err := db.WithContext(ctx).
		Where("id IN ? AND space_id = ?", taskIDs, spaceID).
		Find(&tasks).Error; err != nil {
		return "", nil, fmt.Errorf("fetch referenced tasks: %w", err)
	}
	if len(tasks) == 0 {
		return "", nil, nil
	}

	loaded := make([]int64, 0, len(tasks))
	var sb strings.Builder
	sb.WriteString("\n\n═══════════════════════════════════════════════════\n")
	sb.WriteString("【引用材料 · 用户在本次对话中引用了以下已有总结作为参考】\n")
	sb.WriteString("以下即完整快照 + 产物内容,直接可用,不要反问用户提供 JSON。\n")
	sb.WriteString("═══════════════════════════════════════════════════\n\n")

	for _, task := range tasks {
		// Fetch the latest (per creator) PersonalResult for this task.
		// PersonalResult.uk_task_participant enforces 1 per (task, participant),
		// so we take the caller's own PR (matches user_id) or the first one
		// available for this task if user_id doesn't match (e.g. shared summary).
		var pr model.PersonalResult
		err := db.WithContext(ctx).
			Where("task_id = ? AND user_id = ?", task.ID, userID).
			Order("id DESC").
			First(&pr).Error
		if err != nil {
			// Fall back to any PR for this task (e.g. user is viewing a
			// summary generated by a teammate they can see).
			if err2 := db.WithContext(ctx).
				Where("task_id = ?", task.ID).
				Order("id DESC").
				First(&pr).Error; err2 != nil {
				// No PR at all — skip this task with a marker
				sb.WriteString(fmt.Sprintf("【引用总结 · task_id=%d · %s】(产物尚未生成,跳过)\n\n", task.ID, task.Title))
				continue
			}
		}

		loaded = append(loaded, task.ID)
		sb.WriteString(fmt.Sprintf("─── 引用总结 · task_id=%d · %s ───\n\n", task.ID, task.Title))
		sb.WriteString(fmt.Sprintf("time_range: %s ~ %s\n\n",
			task.TimeRangeStart.Format("2006-01-02"),
			task.TimeRangeEnd.Format("2006-01-02")))

		// Snapshot section: this IS the full snapshot the prompt refers to
		if snap := pr.GetSnapshot(); snap != nil {
			scopeJSON, _ := json.Marshal(snap.Scope)
			sb.WriteString("【快照 · 该总结生成时的完整语境】\n")
			if snap.Requirement != "" {
				sb.WriteString("- 原始需求 (requirement): " + snap.Requirement + "\n")
			}
			sb.WriteString("- 抓取范围 (scope): " + string(scopeJSON) + "\n")
			sb.WriteString(fmt.Sprintf("- 调用工具轨迹 (tool_summary): %v\n", snap.ToolSummary))
			if snap.DataFreshnessNote != "" {
				sb.WriteString("- 数据新鲜度: " + snap.DataFreshnessNote + "\n")
			}
			sb.WriteString("\n")
		} else {
			sb.WriteString("【快照】(该产物为老数据,无快照;仅提供正文,如需扩展请调 fetch_channel 验证)\n\n")
		}

		sb.WriteString("【产物内容 · 完整正文】\n")
		sb.WriteString(pr.Content)
		sb.WriteString("\n\n")

		// Also include citations from the referenced PR so agent knows which
		// messages the original claims were grounded in — critical for refine
		// scenarios that need to preserve or extend citation coverage.
		if cits := pr.GetCitations(); len(cits) > 0 {
			citJSON, _ := json.Marshal(cits)
			sb.WriteString("【原产物 citations】\n")
			sb.WriteString(string(citJSON))
			sb.WriteString("\n\n")
		}

		sb.WriteString("─── 引用结束 ───\n\n")
	}

	if len(loaded) == 0 {
		return "", nil, nil
	}
	return sb.String(), loaded, nil
}

// serializeReferencedTaskIDs converts a slice of task IDs to a JSON string
// suitable for storing in SummaryTask.ReferencedTaskIDs. Returns nil (not
// empty string) when the list is empty so the DB column stays NULL.
func serializeReferencedTaskIDs(ids []int64) *string {
	if len(ids) == 0 {
		return nil
	}
	b, err := json.Marshal(ids)
	if err != nil {
		return nil
	}
	s := string(b)
	return &s
}

// borrowCitationsFromReference returns the citations JSON of the specified
// referenced task's PersonalResult, so a refine-flow save can preserve the
// [n] citation index alignment when its own session had no tool traces.
//
// Returns []model.Citation{} (never nil) if:
//   - the referenced task isn't found in the caller's space
//   - no PR exists for it
//   - the PR's citations_json is empty/invalid
//
// See CHAT-REFERENCE-BASED-DESIGN-v1 §citation preservation.
func (h *AgentSummaryHandler) borrowCitationsFromReference(
	ctx context.Context,
	refTaskID int64,
	spaceID string,
	userID string,
) []model.Citation {
	// Space-scoped lookup: refuse to leak citations across spaces.
	var task model.SummaryTask
	if err := h.db.WithContext(ctx).
		Select("id, space_id").
		Where("id = ? AND space_id = ?", refTaskID, spaceID).
		First(&task).Error; err != nil {
		return []model.Citation{}
	}

	// Prefer caller's own PR (per-creator citation set); fall back to any PR
	// for this task if not found.
	var pr model.PersonalResult
	err := h.db.WithContext(ctx).
		Where("task_id = ? AND user_id = ?", refTaskID, userID).
		Order("id DESC").
		First(&pr).Error
	if err != nil {
		if err2 := h.db.WithContext(ctx).
			Where("task_id = ?", refTaskID).
			Order("id DESC").
			First(&pr).Error; err2 != nil {
			return []model.Citation{}
		}
	}

	cits := pr.GetCitations()
	if cits == nil {
		return []model.Citation{}
	}
	return cits
}
