// Code generated by gen_fence_delims.go. DO NOT EDIT.
// Regenerate with: go generate ./internal/api/handler

package handler

// fenceDelimiterFolds maps angle-bracket and solidus homoglyphs onto their
// ASCII structural equivalent, as strings.NewReplacer pairs.
// Derived from Unicode properties; 31 entries.
var fenceDelimiterFolds = []string{
	"‹", "<", // U+2039 SINGLE LEFT-POINTING ANGLE QUOTATION MARK [name]
	"›", ">", // U+203A SINGLE RIGHT-POINTING ANGLE QUOTATION MARK [name]
	"⁄", "/", // U+2044 FRACTION SLASH [name]
	"∕", "/", // U+2215 DIVISION SLASH [name]
	"〈", "<", // U+2329 LEFT-POINTING ANGLE BRACKET [name]
	"〉", ">", // U+232A RIGHT-POINTING ANGLE BRACKET [name]
	"❬", "<", // U+276C MEDIUM LEFT-POINTING ANGLE BRACKET ORNAMENT [name]
	"❭", ">", // U+276D MEDIUM RIGHT-POINTING ANGLE BRACKET ORNAMENT [name]
	"❮", "<", // U+276E HEAVY LEFT-POINTING ANGLE QUOTATION MARK ORNAMENT [name]
	"❯", ">", // U+276F HEAVY RIGHT-POINTING ANGLE QUOTATION MARK ORNAMENT [name]
	"❰", "<", // U+2770 HEAVY LEFT-POINTING ANGLE BRACKET ORNAMENT [name]
	"❱", ">", // U+2771 HEAVY RIGHT-POINTING ANGLE BRACKET ORNAMENT [name]
	"⟨", "<", // U+27E8 MATHEMATICAL LEFT ANGLE BRACKET [name]
	"⟩", ">", // U+27E9 MATHEMATICAL RIGHT ANGLE BRACKET [name]
	"⦑", "<", // U+2991 LEFT ANGLE BRACKET WITH DOT [name]
	"⦒", ">", // U+2992 RIGHT ANGLE BRACKET WITH DOT [name]
	"⧸", "/", // U+29F8 BIG SOLIDUS [name]
	"⧼", "<", // U+29FC LEFT-POINTING CURVED ANGLE BRACKET [name]
	"⧽", ">", // U+29FD RIGHT-POINTING CURVED ANGLE BRACKET [name]
	"⫽", "/", // U+2AFD DOUBLE SOLIDUS OPERATOR [name]
	"⹊", "/", // U+2E4A DOTTED SOLIDUS [name]
	"〈", "<", // U+3008 LEFT ANGLE BRACKET [name]
	"〉", ">", // U+3009 RIGHT ANGLE BRACKET [name]
	"︿", "<", // U+FE3F PRESENTATION FORM FOR VERTICAL LEFT ANGLE BRACKET [name]
	"﹀", ">", // U+FE40 PRESENTATION FORM FOR VERTICAL RIGHT ANGLE BRACKET [name]
	"﹤", "<", // U+FE64 SMALL LESS-THAN SIGN [NFKC]
	"﹥", ">", // U+FE65 SMALL GREATER-THAN SIGN [NFKC]
	"／", "/", // U+FF0F FULLWIDTH SOLIDUS [NFKC]
	"＜", "<", // U+FF1C FULLWIDTH LESS-THAN SIGN [NFKC]
	"＞", ">", // U+FF1E FULLWIDTH GREATER-THAN SIGN [NFKC]
	"🙼", "/", // U+1F67C VERY HEAVY SOLIDUS [name]
}
