//go:build ignore

// Command gen_fence_delims derives the fence delimiter fold table from Unicode
// character properties and writes fence_delims_table.go.
//
// Run with: go generate ./internal/api/handler
//
// Rationale: rounds 4–10 of #201 repeatedly patched a hand-written homoglyph list
// and repeatedly missed members. A hand-written list is a set the attacker picks
// from the complement. Deriving it from Unicode properties means new members are
// found by re-running this, not by waiting for a reviewer to guess one.
//
// Two derivation rules, both mechanical:
//
//	A. NFKC(r) is exactly "<", ">" or "/" — compatibility equivalence.
//	B. The Unicode NAME marks r as an angle-bracket or solidus homoglyph, with
//	   composite/decorated forms excluded (they do not read as a bare delimiter),
//	   and REVERSE SOLIDUS excluded (a distinct character, not a fence delimiter).
//
// "ANGLE QUOTATION MARK" counts as an angle bracket for rule B: U+2039/U+203A
// (‹›) and U+276E/U+276F (❮❯) are named as quotation marks but render as bare
// angle brackets, so a reader — and a model — sees `‹/文档数据›` as the fence.
// DOUBLE ANGLE forms («») stay excluded: two chevrons do not read as one bracket.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"

	"golang.org/x/text/unicode/norm"
	"golang.org/x/text/unicode/runenames"
)

// excluded name fragments: decorated, enclosed, or composite glyphs that do not
// render as a bare delimiter, plus REVERSE SOLIDUS which is a different character.
var excluded = []string{
	"OVERLAY", "CIRCLE", "CIRCLED", "SQUARED", "APL ", "MUSICAL", "OCR ",
	"MODIFIER", "KANGXI", "TAG ", "INTEGRAL", "PRECEDING", "DOUBLE ANGLE",
	"OVERBAR", "HORIZONTAL STROKE", "NEGATION", "BINARY RELATION", "DIVIDE",
	"REVERSE SOLIDUS", "BACKSLASH",
}

type entry struct {
	r         rune
	to        string
	rule      string
	unicodeNm string
}

func main() {
	var entries []entry
	for r := rune(0); r <= 0x10FFFF; r++ {
		if r >= 0xD800 && r <= 0xDFFF {
			continue // surrogates
		}
		if r == '<' || r == '>' || r == '/' {
			continue // already canonical
		}
		name := runenames.Name(r)
		if name == "" || strings.HasPrefix(name, "<") {
			continue // unassigned / control ranges
		}

		if nf := norm.NFKC.String(string(r)); nf == "<" || nf == ">" || nf == "/" {
			entries = append(entries, entry{r, nf, "NFKC", name})
			continue
		}

		isAngle := strings.Contains(name, "ANGLE BRACKET") || strings.Contains(name, "ANGLE QUOTATION MARK")
		isSolidus := strings.Contains(name, "SOLIDUS") || strings.Contains(name, "SLASH")
		if !isAngle && !isSolidus {
			continue
		}
		skip := false
		for _, frag := range excluded {
			if strings.Contains(name, frag) {
				skip = true
				break
			}
		}
		if skip {
			continue
		}

		var to string
		switch {
		case isSolidus:
			to = "/"
		case strings.Contains(name, "LEFT"):
			to = "<"
		case strings.Contains(name, "RIGHT"):
			to = ">"
		default:
			continue
		}
		entries = append(entries, entry{r, to, "name", name})
	}

	sort.Slice(entries, func(i, j int) bool { return entries[i].r < entries[j].r })

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by gen_fence_delims.go. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "// Regenerate with: go generate ./internal/api/handler\n\n")
	fmt.Fprintf(&buf, "package handler\n\n")
	fmt.Fprintf(&buf, "// fenceDelimiterFolds maps angle-bracket and solidus homoglyphs onto their\n")
	fmt.Fprintf(&buf, "// ASCII structural equivalent, as strings.NewReplacer pairs.\n")
	fmt.Fprintf(&buf, "// Derived from Unicode properties; %d entries.\n", len(entries))
	fmt.Fprintf(&buf, "var fenceDelimiterFolds = []string{\n")
	for _, e := range entries {
		fmt.Fprintf(&buf, "\t%q, %q, // U+%04X %s [%s]\n", string(e.r), e.to, e.r, e.unicodeNm, e.rule)
	}
	fmt.Fprintf(&buf, "}\n")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintln(os.Stderr, "format:", err)
		os.Exit(1)
	}
	if err := os.WriteFile("fence_delims_table.go", src, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write:", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "wrote fence_delims_table.go (%d entries)\n", len(entries))
}
